name: Deploy to AWS

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        TF_VAR_root_db_username: ${{ secrets.ROOT_DB_USERNAME }}
        TF_VAR_root_db_password: ${{ secrets.ROOT_DB_PASSWORD }}
        TF_VAR_service_name: ${{ github.repository }}
      run: terraform plan

    - name: Terraform Apply
      env:
        TF_VAR_root_db_username: ${{ secrets.ROOT_DB_USERNAME }}
        TF_VAR_root_db_password: ${{ secrets.ROOT_DB_PASSWORD }}
        TF_VAR_service_name: ${{ github.repository }}
      run: terraform apply -auto-approve

    - name: Upload Terraform state file
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: terraform.tfstate
